//#define G_N_LINES 91
#define G_N_LINES 106 // AEK

const char *const G_line[G_N_LINES] =
{
  "# Configuration file for dircolors, a utility to help you set the",
  "# " LS_PREFIX "_COLORS environment variable used by " LS_PROGRAM " with the --color option.",
  "",
  "# The keywords COLOR, OPTIONS, and EIGHTBIT (honored by the",
  "# slackware version of dircolors) are recognized but ignored.",
  "",
  "# Ported to Microsoft Windows by Alan Klietz (alank@algintech.com)",
  "",
  "# Below, there should be one TERM entry for each termtype that is colorizable",
  "TERM linux",
  "TERM linux-c",
  "TERM mach-color",
  "TERM console",
  "TERM con132x25",
  "TERM con132x30",
  "TERM con132x43",
  "TERM con132x60",
  "TERM con80x25",
  "TERM con80x28",
  "TERM con80x30",
  "TERM con80x43",
  "TERM con80x50",
  "TERM con80x60",
  "TERM xterm",
  "TERM xterm-debian",
  "TERM rxvt",
  "TERM screen",
  "TERM screen-w",
  "TERM vt100",
  "",
  "# Below are the color init strings for the basic file types. A color init",
  "# string consists of one or more of the following numeric codes:",
  "# Attribute codes:",
  "# 00=none 01=bold 04=underscore 05=blink 07=reverse 08=concealed",
  "# Text color codes:",
  "# 30=black 31=red 32=green 33=yellow 34=blue 35=magenta 36=cyan 37=white",
  "# Background color codes:",
  "# 40=black 41=red 42=green 43=yellow 44=blue 45=magenta 46=cyan 47=white",
  "NORMAL 00     # global default, although everything should be something.",
  "FILE 00       # normal file",
  "DIR 01;32     # directory",
  "LINK 01;34    # symbolic link.  (If you set this to 'target' instead of a",
  "              # numerical value, the color is as for the file pointed to.)",
  "FIFO 40;33    # pipe",
  "SOCK 01;35    # socket",
  "DOOR 01;35    # door",
  "BLK 40;33     # block device driver",
  "CHR 40;33     # character device driver",
  "ORPHAN 40;31;01 # symlink to nonexistent file",
  "",
  "# This is for files with execute permission:",
  "EXEC 01;33",
  "",
  "# Highlight recently modified files - underscore",
  "RECENT ;04   # leading semicolon required",
  "",
  "# Hightlight compressed files - bright cyan",
  "COMPRESSED ;01;36  # leading semicolon required",
  "",
  "# Highlight files with embedded streams - blue",
  "STREAMS ;01;34  # leading semicolon required",
  "",
  "# List any file extensions like '.gz' or '.tar' that you would like ls",
  "# to colorize below. Put the extension, a space, and the color init string.",
  "# (and any comments you want to add after a '#')",
  "",
  "# DOS-style suffixes:",
  ".cmd 01;33 # executables (bright yellow)",
  ".bat 01;33",
  ".exe 01;33",
  ".com 01;33",
  ".ps1 01;33",
  "#.dll 01;33",
  "#.sys 01;33",
  "",
  ".tar 01;36 # archives or compressed (bright cyan)",
  ".tgz 01;36",
  ".arj 01;36",
  ".taz 01;36",
  ".lzh 01;36",
  ".zip 01;36",
  ".z   01;36",
  ".Z   01;36",
  ".gz  01;36",
  ".bz2 01;36",
  ".deb 01;36",
  ".rpm 01;36",
  "",
  "# image formats (magenta)",
  ".jpg 01;35",
  ".png 01;35",
  ".gif 01;35",
  ".bmp 01;35",
  ".ppm 01;35",
  ".tga 01;35",
  ".xbm 01;35",
  ".xpm 01;35",
  ".tif 01;35",
  ".cdr 01;35",
  ".mpg 01;35",
  ".mp4 01;35",
  ".wmv 01;35",
  ".avi 01;35",
  ".fli 01;35",
  ".gl 01;35",
  ".dl 01;35"
};
